# See the documentation for more information:
# https://packit.dev/docs/configuration/

---
actions:
  create-archive:
    - bash -c "tito build --tgz --test -o ."
    - bash -c "ls -1t ./*.tar.gz | head -n 1"
  get-current-version:
    - bash -c "grep ^Version \"$PACKIT_CONFIG_PACKAGE_NAME.spec\" | awk '{ print $2 }'"

packages:
  mock:
    specfile_path: mock.spec
    paths:
      - ./mock
    downstream_package_name: mock
    upstream_tag_template: mock-{version}
  mock-core-configs:
    specfile_path: mock-core-configs.spec
    paths:
      - ./mock-core-configs
    downstream_package_name: mock-core-configs
    upstream_tag_template: mock-core-configs-{version}
srpm_build_deps:
  - tito
  - git

jobs:
  - job: copr_build
    trigger: pull_request
    packages:
      - mock
      - mock-core-configs
    metadata:
      targets:
        - fedora-rawhide
        - fedora-latest-stable

  - job: tests
    trigger: pull_request
    targets:
      - fedora-latest-stable
    # We don't want to run two test runs; so we limit this to a single package
    packages:
      - mock
